
language: php

php:
  - 8.0.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - if [ $(phpenv version-name) == "8.0.1" ]; then vendor/bin/phpunit 

after_script:
  - if [ $(phpenv version-name) == "8.0.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) == "8.0.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi